### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by anheru88** [Porto-SAP/Environment#1]
Hi, @Mahmoudz, first of all, you are amazing, I try tu understand how to work Porto, and i think is a excelent idea. 

I have a problem with this container, i install normaly, but when run somo artisan command, the console show this message:

```
[ReflectionException]
Class App\Http\Controllers\EnvController does not exist
```
My composer.json file inside Containers is this:

```
{
  "require": {
    "porto-sap/welcome": "dev-master",
    "porto-sap/user": "dev-master",
    "porto-sap/authentication": "dev-master",
    "porto-sap/application": "dev-master",
    "porto-sap/authorization": "dev-master",
    "porto-sap/social-auth": "dev-master",
    "porto-sap/debugger": "dev-master",
    "porto-sap/email": "dev-master",
    "porto-sap/contact": "dev-master",
    "porto-sap/country": "dev-master",
    "porto-sap/payment": "dev-master",
    "porto-sap/paypal": "dev-master",
    "porto-sap/stripe": "dev-master",
    "porto-sap/settings": "dev-master",
    "porto-sap/environment": "dev-master"
  },
  "extra": {
    "merge-plugin": {
      "require": [

      ]
    }
  }
}
```

I don't know if i need register some provider or i miss one step.

Thanks for this package.

**Comment by Mahmoudz** [comment]
Hi, @anheru88 thank you for your message. There's nothing wrong with your steps. The problem is with `porto-sap/environment` just remove `"porto-sap/environment": "dev-master"` line and you should be fine after running `composer update`. (If you get yourself a copy of the latest version, this should not be included by default.) I haven't tried to fix that container yet. This container is just wrapper for a package that allows modifying the `.env` file from the browser.
